export const STATUS_UPLOADED = 'uploaded'
export const STATUS_INVITED = 'invited'
export const STATUS_DECLINED = 'declined'
export const STATUS_SIGNED = 'signed'
export const STATUS_PROCESSING = 'processing'
export const STATUS_DONE = 'done'
